package main

import (
	"context"
	"fmt"
	"language-learning-app/config"
	"language-learning-app/core/agents"
	"language-learning-app/core/llm"
	"language-learning-app/handlers"
	"language-learning-app/middleware"
	"language-learning-app/migrations"
	"language-learning-app/services"
	"language-learning-app/storage"
	"language-learning-app/utils"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"

	_ "language-learning-app/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title						Language Learning App
// @version					1.0
// @description				This is an api for the language learning app
// @host						localhost:8081
// @BasePath					/
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description				Type 'Bearer <token>' to correctly set the JWT
func main() {
	// Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		panic(err)
	}

	// Start migration as soon as the application starts
	err = migrations.Run(cfg.Database.Filepath)
	if err != nil {
		panic(err)
	}

	// Initialize logger
	utils.InitLogger(cfg.LogLevel)

	llmCore := llm.NewLlm(cfg.Llm)

	// Initialize database
	db, err := storage.InitDb(cfg.Database.Filepath)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	// Create user repository, service, and handler
	userGrammarRepository := storage.NewUserGrammarRepository(db)
	userWordRepository := storage.NewUserWordRepository(db)
	userLessonRepository := storage.NewUserLessonRepository(db)
	userRepository := storage.NewUserRepository(db)

	lessonAgent := agents.NewLessonAgent(llmCore)
	exerciseAgent := agents.NewExerciseAgent(llmCore)
	chatbotAgent := agents.NewChatbotAgent(llmCore)

	exerciseService := services.NewExerciseService(exerciseAgent, userLessonRepository, userGrammarRepository, userWordRepository)
	userLessonsService := services.NewUserLessonService(userLessonRepository, lessonAgent, userGrammarRepository, userWordRepository)
	userGrammarService := services.NewUserGrammarService(userGrammarRepository)
	userWordService := services.NewUserWordService(userWordRepository)
	userService := services.NewUserService(userRepository, userGrammarRepository, userWordRepository)
	chatbotService := services.NewChatbotService(chatbotAgent)

	exerciseHandler := handlers.NewExerciseHandler(exerciseService, userService)
	userLessonsHandler := handlers.NewUserLessonHandler(userLessonsService, userService)
	userGrammarHandler := handlers.NewUserGrammarHandler(userGrammarService, userService)
	userWordHandler := handlers.NewUserWordHandler(userWordService, userService)
	userHandler := handlers.NewUserHandler(userService)
	authHandler := handlers.NewAuthHandler(userService)
	chatbotHandler := handlers.NewChatbotHandler(chatbotService, userService)

	// Create router
	r := chi.NewRouter()

	// ===== Middleware =====
	r.Use(chiMiddleware.RequestID)
	r.Use(middleware.LoggerMiddleware)
	r.Use(middleware.MetricsMiddleware)
	r.Use(chiMiddleware.Recoverer)
	r.Use(middleware.CorsMiddleware())
	r.Use(middleware.RateLimiterMiddleware())
	r.Use(chiMiddleware.AllowContentType("application/json", "text/plain"))
	r.Use(chiMiddleware.Timeout(60 * time.Second))

	// ===== Static files ====
	staticDir := http.Dir("resources/static")
	r.Handle("/ui/*", http.StripPrefix("/ui/", http.FileServer(staticDir)))

	// ===== Redirects ====
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/ui/", http.StatusFound) // Use http.StatusFound for a temporary redirect (302)
	})

	// ===== Routes =====
	r.Get("/health", handlers.HealthCheckHandler)
	r.Handle("/metrics", handlers.MetricsHandler())

	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))

	r.Route("/auth", func(r chi.Router) {
		r.Post("/token", authHandler.GetAuthTokenHandler)
	})

	r.Route("/user", func(r chi.Router) {
		r.Use(middleware.JWTAuth)
		r.Get("/profile", userHandler.GetUserProfileHandler)
		r.Patch("/profile", userHandler.UpdateUserSettingsHandler)
		r.Get("/status/report", userHandler.GetUserStatusReport)
	})

	r.Route("/resources", func(r chi.Router) {
		r.Use(middleware.JWTAuth)
		r.Post("/exercise/usage/grade", exerciseHandler.GradeUsageHandler)
		r.Post("/exercise/translation/generate", exerciseHandler.GenerateTranslationExerciseHandler)
		r.Post("/exercise/translation/grade", exerciseHandler.GradeTranslationExerciseHandler)
		r.Post("/exercise/reading-comprehension/generate", exerciseHandler.GenerateReadingComprehensionExerciseHandler)
		r.Post("/exercise/reading-comprehension/grade", exerciseHandler.GradeReadingComprehensionResponseHandler)
		r.Post("/exercise/dialogue/init", exerciseHandler.GenerateDialogueInitExerciseHandler)
		r.Post("/exercise/dialogue/continue", exerciseHandler.GenerateDialogueContinuationExerciseHandler)
		r.Get("/lessons", userLessonsHandler.GetLessonsHandler)
		r.Post("/lessons/generate", userLessonsHandler.GenerateLessonHandler)
		r.Get("/grammar", userGrammarHandler.GetGrammarPatternsHandler)
		r.Get("/grammar/search", userGrammarHandler.GetGrammarPatternsByPatternHandler)
		r.Get("/words", userWordHandler.GetWordsHandler)
	})

	r.Route("/chatbot", func(r chi.Router) {
		r.Use(middleware.JWTAuth)
		r.Post("/response", chatbotHandler.GetResponseHandler)
	})

	// Start server
	serverAddr := fmt.Sprintf(":%d", cfg.Server.Port)
	server := &http.Server{Addr: serverAddr, Handler: r}

	// Listen for OS signals to perform a graceful shutdown
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	go func() {
		fmt.Printf("✅ Server running on http://localhost%s\n", serverAddr)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			utils.Logger.Error("Server failed to start", "error", err)
			os.Exit(1)
		}
	}()

	<-stop // Wait for OS signal

	utils.Logger.Info("Shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		utils.Logger.Error("Server graceful shutdown failed", "error", err)
		os.Exit(1)
	}

	utils.Logger.Info("Server gracefully stopped")

}
