package main

import (
	"context"
	"fmt"
	"language-learning-app/agents"
	"language-learning-app/config"
	"language-learning-app/core/llm"
	"language-learning-app/handlers"
	"language-learning-app/middleware"
	"language-learning-app/services"
	"language-learning-app/storage"
	"language-learning-app/utils"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"runtime"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"

	_ "language-learning-app/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title			Language Learning App
// @version		1.0
// @description	This is an api for the language learning app
// @host			localhost:8080
// @BasePath		/
func main() {
	// Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		panic(err)
	}

	// Initialize logger
	utils.InitLogger(cfg.LogLevel)

	llmCore := llm.NewLlamaCpp(cfg.Llm.BaseUrl, cfg.Llm.Model)

	// Initialize database
	db, err := storage.InitDb(cfg.Database.Filepath)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	// Create user repository, service, and handler
	grammarMasteryRepository := storage.NewGrammarMasteryRepository(db)
	vocabMasteryRepository := storage.NewVocabularyMasteryRepository(db)
	lessonRepository := storage.NewLessonRepository(db)
	exerciseRepository := storage.NewExerciseRepository(db)

	lessonAgent := agents.NewLessonAgent(llmCore, lessonRepository, vocabMasteryRepository, grammarMasteryRepository)
	practiceAgent := agents.NewPracticeAgent(llmCore, lessonRepository, exerciseRepository)

	agentsService := services.NewAgentService(lessonAgent, practiceAgent)
	lessonsService := services.NewLessonService(lessonRepository)
	grammarService := services.NewGrammarService(grammarMasteryRepository)
	vocabularyService := services.NewVocabularyService(vocabMasteryRepository)

	angentsHandler := handlers.NewAgentHandler(agentsService)
	lessonsHandler := handlers.NewLessonHandler(lessonsService)
	grammarHandler := handlers.NewGrammarHandler(grammarService)
	vocabularyHandler := handlers.NewVocabularyHandler(vocabularyService)

	// Create router
	r := chi.NewRouter()

	// ===== Middleware =====
	r.Use(chiMiddleware.RequestID)
	r.Use(middleware.LoggerMiddleware)
	r.Use(middleware.MetricsMiddleware)
	r.Use(chiMiddleware.Recoverer)
	r.Use(middleware.CorsMiddleware())
	r.Use(middleware.RateLimiterMiddleware())
	r.Use(chiMiddleware.AllowContentType("application/json", "text/plain"))
	r.Use(chiMiddleware.Timeout(60 * time.Second))

	// ===== Static files ====
	_, b, _, _ := runtime.Caller(0)
	basepath := filepath.Dir(b)
	staticDir := http.Dir(filepath.Join(basepath, "resources/static"))
	r.Handle("/ui/*", http.StripPrefix("/ui/", http.FileServer(staticDir)))

	// ===== Redirects ====
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/ui/", http.StatusFound) // Use http.StatusFound for a temporary redirect (302)
	})

	// ===== Routes =====
	r.Get("/health", handlers.HealthCheckHandler)
	r.Handle("/metrics", handlers.MetricsHandler())

	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))

	r.Route("/agents", func(r chi.Router) {
		r.Use(middleware.BasicAuth)
		r.Post("/lessons", angentsHandler.GenerateLessonHandler)
		r.Post("/exercises", angentsHandler.GenerateExerciseHandler)
	})

	r.Route("/resources", func(r chi.Router) {
		r.Use(middleware.BasicAuth)
		r.Get("/lessons", lessonsHandler.GetLessonsHandler)
		r.Get("/lessons/search", lessonsHandler.GetLessonsByGrammarHandler)
		r.Get("/grammar", grammarHandler.GetGrammarPatternsHandler)
		r.Get("/grammar/search", grammarHandler.GetGrammarPatternsByPatternHandler)
		r.Get("/vocabulary", vocabularyHandler.GetVocabularyHandler)
	})

	// Start server
	serverAddr := fmt.Sprintf(":%d", cfg.Server.Port)
	server := &http.Server{Addr: serverAddr, Handler: r}

	// Listen for OS signals to perform a graceful shutdown
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	go func() {
		fmt.Printf("✅ Server running on http://localhost%s\n", serverAddr)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			utils.Logger.Error("Server failed to start", "error", err)
			os.Exit(1)
		}
	}()

	<-stop // Wait for OS signal

	utils.Logger.Info("Shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		utils.Logger.Error("Server graceful shutdown failed", "error", err)
		os.Exit(1)
	}

	utils.Logger.Info("Server gracefully stopped")

}
